#!/bin/bash

[ -n "$NOTICE_DATE_FORMAT" ] && FORMAT=+${NOTICE_DATE_FORMAT}
NOW=${NOTICE_DATE-`date $FORMAT`}
DELIMITER=${NOTICE_SEP-' -- '}
LOG=${NOTICE_LOG-"$HOME/.notice"}

echo -n "${NOW}${DELIMITER}" >> $LOG

if [ $# -gt 0 ]; then
    echo "${@}" >> $LOG
else
    ( echo; cat -; echo "$DELIMITER" ) >> $LOG
fi
